# Generated by Django 2.1.5 on 2019-02-11 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('idVal', models.SlugField()),
                ('category', models.SlugField()),
                ('content', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('introContent', models.TextField(max_length=500)),
                ('title', models.TextField(max_length=100)),
                ('idVal', models.SlugField()),
                ('category', models.SlugField()),
            ],
        ),
    ]
