# Generated by Django 2.1.5 on 2019-02-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_post_pictureid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='recent1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='recent2',
            field=models.BooleanField(default=False),
        ),
    ]
