# Generated by Django 3.0 on 2019-12-05 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageposts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=200)),
                ('idVal', models.SlugField()),
                ('category', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=200)),
                ('introContent', models.TextField(max_length=500)),
                ('idVal', models.SlugField()),
                ('category', models.SlugField()),
                ('pictureID', models.CharField(max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('recent1', models.BooleanField(default=False)),
                ('recent2', models.BooleanField(default=False)),
            ],
        ),
    ]
